### ISSUE TITLE
terrafrom plan command not taking -out option

### ISSUE THREAD

**Issue by narasimha18sv** [beelit94/python-terraform#15]
options={"-out": plan_dir+os.sep+temp}
terraform.plan(dir_or_plan=plan_dir, detailed_exitcode=IsFlagged, kwargs=options)

above is the code which i wrote to generate terraform plan to a output file. 
but from the debug logs I can see log as it generrated -out file but I dont see that file in the command execution.

Log:

DEBUG:python_terraform:variables wrote to tempfile: {'-out': 'D:\\temp\\3603c548-57aa-4364-9d68-63a6582abd20\\3603c548-57aa-4364-9d68-63a6582abd20'}
variables wrote to tempfile: {'-out': 'D:\\temp\\3603c548-57aa-4364-9d68-63a6582abd20\\3603c548-57aa-4364-9d68-63a6582abd20'}
DEBUG:python_terraform:command: terraform plan -var-file=C:\Users\nsv\AppData\Local\Temp\tmpx7bjb7rc -no-color -input=false -var-file=C:\Users\nsv\AppData\Local\Temp\tmpuabumy3d -detailed-exitcode D:\temp\3603c548-57aa-4364-9d68-63a6582abd20
command: terraform plan -var-file=C:\Users\nsv\AppData\Local\Temp\tmpx7bjb7rc -no-color -input=false -var-file=C:\Users\nsv\AppData\Local\Temp\tmpuabumy3d -detailed-exitcode D:\temp\3603c548-57aa-4364-9d68-63a6582abd20

When I checked the folder i dont see that file got created.

**Comment by beelit94** [comment]
@narasimha18sv Thank you for your report.
For this one, what you trying to achieve should be
```
out_path = plan_dir+os.sep+temp
terraform.plan(dir_or_plan=plan_dir, detailed_exitcode=IsFlagged, out=out_path)
```
or
```
options={"out": plan_dir+os.sep+temp}
terraform.plan(dir_or_plan=plan_dir, detailed_exitcode=IsFlagged, **options)
```
These will translate to output command
```
terraform plan -var-file=/var/folders/92/4fzkp03j4b3fff5rppp4ns780000gp/T/tmpr8e9mjba -no-color -input=false -out=<YOUR_OUTPUT_PATH> -detailed-exitcode
```

Because kwargs in python here is to accept an undefined keywords parameter, passing `kwargs=options` won't pass each key value pair in "options" as parameter, instead, it will pass a parameter called "kwargs" and its value is "options". See https://pythontips.com/2013/08/04/args-and-kwargs-in-python-explained/ for more references.

And in the library we intentionally treat "dict" type parameter as the variables we want to pass to terraform, because we assume that's the only complicated dictionary needed for those commands.
That's why you see 
`variables wrote to tempfile: {'-out': 'D:\temp\3603c548-57aa-4364-9d68-63a6582abd20\3603c548-57aa-4364-9d68-63a6582abd20'}` in the log

**Comment by beelit94** [comment]
BTW we didn't handle when there's an empty space in the path, the command call would fail.
This will be a bug, we will fix it.

**Comment by beelit94** [comment]
empty space is fixed by https://github.com/beelit94/python-terraform/pull/17

**Comment by beelit94** [comment]
@narasimha18sv any further question for this?

**Comment by narasimha18sv** [comment]
no. everything is working fine for me.
